//! CUE sheet generation for ripped discs.
//!
//! A CUE sheet is a plain-text metadata file that describes the track layout
//! of a disc. Players like foobar2000, VLC, and most archiving tools can use
//! it to address individual tracks within a single multi-track image, or
//! alongside split files (one per track) for accurate gapless playback.
//!
//! We'll generate the "split file" variant — one FILE entry per track - since
//! cdrip outputs one file per track rather than a single disc image.
//!
//! Format reference: https://wiki.hydrogenaud.io/index.php?title=Cue_sheet

use crate::{
    encoder::OutputFormat,
    toc::{DiscToc, TrackInfo},
};
use std::{
    fs::File,
    io::{self, BufWriter, Write},
    path::{Path, PathBuf},
};

// CUE metadata
/// Optional disc-level metadata to embed in the CUE sheet.
/// All fields are optional — cdrip doesn't force you to enter anything.
/// If MusicBrainz lookup is added in v1 this struct gets populated automatically.
#[derive(Debug, Clone, Default)]
pub struct CueMetadata {
    pub album_title: Option<String>,
    pub album_artist: Option<String>,
    pub catalog: Option<String>,
    pub track_titles: Vec<Option<String>>,
    pub track_artists: Vec<Option<String>>,
}

impl CueMetadata {
    /// Build a metadata stub with the right Vec lengths for `track_count` tracks.
    pub fn empty(track_count: u8) -> Self {
        Self {
            track_titles: vec![None; track_count as usize],
            track_artists: vec![None; track_count as usize],
            ..Default::default()
        }
    }

    pub fn track_title(&self, track_num: u8) -> Option<&str> {
        self.track_titles
            .get((track_num - 1) as usize)
            .and_then(|t| t.as_deref())
    }

    pub fn track_artist(&self, track_num: u8) -> Option<&str> {
        self.track_artists
            .get((track_num - 1) as usize)
            .and_then(|a| a.as_deref())
    }
}

// CUE generation
/// Generate a CUE sheet and write it to `output/disc.cue`.
/// Produces one `FILE` block per track (split-file CUE, not a disc-image CUE).
/// Timestamps use the MSF format required by the spec: `MM:SS:FF`
/// where FF is frames (0–74, 75 frames = 1 second).
pub fn write_cue(
    toc: &DiscToc,
    format: OutputFormat,
    output_dir: &Path,
    meta: &CueMetadata,
) -> io::Result<PathBuf> {
    let cue_path = output_dir.join("disc.cue");
    let file = File::create(&cue_path)?;
    let mut w = BufWriter::new(file);

    writeln!(w, "REM GENERATED BY CDRIP.RS")?;
    writeln!(w, "REM TOOL CDRIP.RS https://codeberg.org/Kazooki123/cdrip.rs")?;

    if let Some(catalog) = &meta.catalog {
        writeln!(w, "CATALOG {}", catalog)?;
    }
    if let Some(artist) = &meta.album_artist {
        writeln!(w, "PERFORMER \"{}\"", escape_cue(artist))?;
    }
    if let Some(title) = &meta.album_title {
        writeln!(w, "TITLE \"{}\"", escape_cue(title))?;
    }

    for track in &toc.tracks {
        let filename = format!("track{:02}.{}", track.number, format.extension());

        writeln!(w, "FILE \"{}\" WAVE", filename)?;
        writeln!(w, "  TRACK {:02} AUDIO", track.number)?;

        if let Some(title) = meta.track_title(track.number) {
            writeln!(w, "    TITLE \"{}\"", escape_cue(title))?;
        }
        if let Some(artist) = meta.track_artist(track.number) {
            writeln!(w, "    PERFORMER \"{}\"", escape_cue(artist))?;
        }

        // INDEX 01 - start of audio. For split files each track starts at 00:00:00.
        writeln!(w, "    INDEX 01 {}", msf_cue(track))?;
    }

    w.flush()?;
    Ok(cue_path)
}

// HELPERS
/// Format a track's start MSF as a CUE timestamp string `MM:SS:FF`.
/// For split-file CUE sheets each track file starts at 00:00:00 because
/// the file begins at the track boundary. We still embed the disc-absolute
/// MSF as a REM comment so the data is preserved.
#[allow(unused)]
fn msf_cue(track: &TrackInfo) -> String {
    "00:00:00".to_string()
}
#[allow(dead_code)]
pub fn lba_to_msf_string(lba: u32) -> String {
    let total_frames = lba + 150;
    let minutes = total_frames / (75 * 60);
    let seconds = (total_frames / 75) % 60;
    let frames = total_frames % 75;
    format!("{:02}:{:02}:{:02}", minutes, seconds, frames)
}

fn escape_cue(s: &str) -> String {
    s.replace('"', "'")
}

// TESTS
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lba_to_msf_lead_in_offset() {
        // LBA 0 → 150 total frames → 00:02:00
        assert_eq!(lba_to_msf_string(0), "00:02:00");
    }

    #[test]
    fn lba_to_msf_one_second() {
        // LBA 75 → 225 total frames → 00:03:00
        assert_eq!(lba_to_msf_string(75), "00:03:00");
    }

    #[test]
    fn escape_cue_quotes() {
        assert_eq!(escape_cue("AC/DC \"Back in Black\""), "AC/DC 'Back in Black'");
    }

    #[test]
    fn escape_cue_clean() {
        assert_eq!(escape_cue("Nevermind"), "Nevermind");
    }
}
